# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Computational Psycholinguistic Discussions (C.Psyd)
email: mv443@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  We are interested in the intersection of computational linguistics and psycholinguistics. By building computational models to predict human language processing behavior (e.g., reading times), we can study the linguistic features that impact human processing decisions. Relatedly, C.Psyd members use psycholinguistic techniques to study the strategies used by neural networks to produce high accuracy in different language contexts, which gives us insights as to when different strategies might be employed by humans.
baseurl: "https://vansky.github.io/cpsyd.github.io/"
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

